global:
  scrape_interval: 5s  # Set the scrape interval to every 5 seconds
  evaluation_interval: 5s  # Evaluate rules every 5 seconds

scrape_configs:
  - job_name: 'ics_normal'
    static_configs:
      - targets: ['localhost:8000']
        labels:
          instance: 'ics_normal'
          environment: 'simulation'
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: '(.*)'
        replacement: 'normal_${1}'

  - job_name: 'ics_attack'
    static_configs:
      - targets: ['localhost:8001']
        labels:
          instance: 'ics_attack'
          environment: 'simulation'
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: '(.*)'
        replacement: 'attack_${1}'
